### PR TITLE
Close tags specifically and add blink

### PR DESCRIPTION
**Pull request by lwolfsonkin**
Added 2 things:

- Closing tags are now specific:
  - `</b>` only ends bold
  - `</bg>` only normalizes background color (leaves foreground and style alone)
  - etc
- Adds blinking tag denoted with `bl`

### CODE REVIEW

**Comment by lwolfsonkin** [comment]
Note that I didn't really play with the tests at all because, although they must change, the `fishtape` testing framework doesn't seem to work at all on my machine. Even on the initial master branch of this repo, running:

```
fishtape tests/cprintf.fish
```

results in

```
- (line 61): Missing end to balance this function definition
function __fishtape@total;	if test $__fishtape_count -eq 0;        fishtape_cleanup;        exit 1;    end;;    printf "\n1..%s\n" $__fishtape_count;    printf "# tests %s\n" $__fishtape_count;    printf "# pass  %s\n" (math $__fishtape_count - $__fishtape_fails);;    if test $__fishtape_fails -gt 0;        printf "# fail  %s\n" $__fishtape_fails;        fishtape_cleanup;        exit 1;    end;;    fishtape_cleanup;    printf "\n# ok\n"
^
from sourcing file -
	called on standard input

source: Error while reading file '-'
```


 EDIT: Nevermind, it seems that `fisher` had for some reason installed an ancient version of `fishtape`. When I updated, it worked just fine.

**Comment by lwolfsonkin** [comment]
Also, the newly introduced codes for closing tags (as well as the blinking tags) chosen within the code are from the [ANSI Escape Codes](https://en.wikipedia.org/wiki/ANSI_escape_code#SGR_(Select_Graphic_Rendition)_parameters), a subset which unfortunately the `set_color` command doesn't support. Thus, they had to be printed directly.

**Comment by Markcial** [comment]
Looks good for me

**Comment by Markcial** [comment]
Great contribution! thanks!! :tada: :tada:

**Pull request merged**
